// https://remixicon.com网址上的图标class
const icons = [
  // Arrows
  "ri-arrow-up-line",
  "ri-arrow-down-line",
  "ri-arrow-right-line",
  "ri-arrow-left-line",

  "ri-arrow-up-fill",
  "ri-arrow-down-fill",
  "ri-arrow-right-fill",
  "ri-arrow-left-fill",

  "ri-arrow-up-circle-line",
  "ri-arrow-down-circle-line",
  "ri-arrow-right-circle-line",
  "ri-arrow-left-circle-line",

  "ri-arrow-up-circle-fill",
  "ri-arrow-down-circle-fill",
  "ri-arrow-right-circle-fill",
  "ri-arrow-left-circle-fill",

  "ri-arrow-up-s-line",
  "ri-arrow-down-s-line",
  "ri-arrow-right-s-line",
  "ri-arrow-left-s-line",

  "ri-arrow-up-s-fill",
  "ri-arrow-down-s-fill",
  "ri-arrow-right-s-fill",
  "ri-arrow-left-s-fill",
  
  "ri-skip-up-line",
  "ri-skip-down-line",
  "ri-skip-right-line",
  "ri-skip-left-line",

  "ri-skip-up-fill",
  "ri-skip-down-fill",
  "ri-skip-right-fill",
  "ri-skip-left-fill",

  "ri-arrow-left-right-line",
  "ri-arrow-up-down-line",

  "ri-arrow-up-double-line",
  "ri-arrow-down-double-line",
  "ri-arrow-right-double-line",
  "ri-arrow-left-double-line",
  
  "ri-arrow-go-back-line",
  "ri-arrow-go-forward-line",
  "ri-arrow-turn-forward-line",
  "ri-arrow-turn-back-line",

  "ri-drag-move-2-fill",

  // Buildings
  "ri-home-2-line",
  "ri-home-2-fill",
  "ri-building-line",
  "ri-building-fill",
  "ri-hotel-line",
  "ri-hotel-fill",
  "ri-school-line",
  "ri-school-fill",
  "ri-government-line",
  "ri-government-fill",
  "ri-bank-line",
  "ri-bank-fill",
  "ri-store-line",
  "ri-store-fill",
  "ri-ancient-gate-line",
  "ri-ancient-gate-fill",

  // Business
  "ri-mail-line",
  "ri-mail-fill",
  "ri-mail-open-line",
  "ri-mail-open-fill",
  "ri-inbox-2-line",
  "ri-inbox-2-fill",
  "ri-cloud-line",
  "ri-cloud-fill",
  "ri-cloud-off-line",
  "ri-cloud-off-fill",
  "ri-profile-line",
  "ri-profile-fill",
  "ri-archive-line",
  "ri-archive-fill",
  "ri-archive-drawer-line",
  "ri-archive-drawer-fill",
  "ri-award-line",
  "ri-award-fill",
  "ri-verified-badge-line",
  "ri-verified-badge-fill",
  "ri-bar-chart-line",
  "ri-bar-chart-fill",
  "ri-pie-chart-line",
  "ri-pie-chart-fill",
  "ri-line-chart-line",
  "ri-line-chart-fill",
  "ri-bookmark-line",
  "ri-bookmark-fill",
  "ri-briefcase-4-line",
  "ri-briefcase-4-fill",
  "ri-calculator-line",
  "ri-calculator-fill",
  "ri-calendar-2-line",
  "ri-calendar-2-fill",
  "ri-customer-service-2-line",
  "ri-customer-service-2-fill",
  "ri-flag-2-line",
  "ri-flag-2-fill",
  "ri-honour-line",
  "ri-honour-fill",
  "ri-slideshow-line",
  "ri-slideshow-fill",
  "ri-slideshow-3-line",
  "ri-slideshow-3-fill",
  "ri-stack-line",
  "ri-stack-fill",
  "ri-megaphone-line",
  "ri-megaphone-fill",

  // Communication
  "ri-message-2-line",
  "ri-message-2-fill",
  "ri-discuss-line",
  "ri-discuss-fill",

  // Design
  "ri-edit-line",
  "ri-edit-fill",
  "ri-edit-box-line",
  "ri-edit-box-fill",
  "ri-sip-line",
  "ri-sip-fill",
  "ri-scissors-line",
  "ri-scissors-fill",
  "ri-scissors-cut-line",
  "ri-scissors-cut-fill",
  "ri-focus-3-line",
  "ri-focus-3-fill",
  "ri-paint-line",
  "ri-paint-fill",
  "ri-palette-line",
  "ri-palette-fill",
  "ri-shape-line",
  "ri-shape-fill",
  "ri-magic-line",
  "ri-magic-fill",
  "ri-hammer-line",
  "ri-hammer-fill",
  "ri-tools-line",
  "ri-tools-fill",
  "ri-shapes-line",
  "ri-shapes-fill",

  // Development
  "ri-bug-line",
  "ri-bug-fill",
  "ri-code-s-slash-line",
  "ri-code-s-slash-fill",
  "ri-terminal-box-line",
  "ri-terminal-box-fill",
  "ri-command-line",
  "ri-command-fill",
  "ri-cursor-line",
  "ri-cursor-fill",
  "ri-git-commit-line",
  "ri-git-commit-fill",
  "ri-git-pull-request-line",
  "ri-git-pull-request-fill",
  "ri-git-merge-line",
  "ri-git-merge-fill",
  "ri-git-branch-line",
  "ri-git-branch-fill",
  "ri-git-close-pull-request-line",
  "ri-git-close-pull-request-fill",
  "ri-git-repository-line",
  "ri-git-repository-fill",
  "ri-git-repository-commits-line",
  "ri-git-repository-commits-fill",
  "ri-git-repository-private-line",
  "ri-git-repository-private-fill",
  "ri-html5-line",
  "ri-html5-fill",
  "ri-css3-line",
  "ri-css3-fill",
  "ri-javascript-line",
  "ri-javascript-fill",

  // Device
  "ri-computer-line",
  "ri-computer-fill",
  "ri-phone-line",
  "ri-phone-fill",
  "ri-instance-line",
  "ri-instance-fill",
  "ri-database-2-line",
  "ri-database-2-fill",
  "ri-server-line",
  "ri-server-fill",
  "ri-save-line",
  "ri-save-fill",
  "ri-battery-charge-line",
  "ri-battery-charge-fill",
  "ri-mouse-line",
  "ri-mouse-fill",
  "ri-gamepad-line",
  "ri-gamepad-fill",
  "ri-rotate-lock-line",
  "ri-rotate-lock-fill",
  "ri-restart-line",
  "ri-restart-fill",
  "ri-shut-down-line",
  "ri-shut-down-fill",
  "ri-qr-code-line",
  "ri-qr-code-fill",
  "ri-qr-scan-2-line",
  "ri-qr-scan-2-fill",
  "ri-rss-line",
  "ri-rss-fill",
  "ri-bluetooth-line",
  "ri-bluetooth-fill",
  "ri-wifi-line",
  "ri-wifi-fill",
  "ri-dashboard-3-line",
  "ri-dashboard-3-fill",
  "ri-usb-line",
  "ri-usb-fill",
  "ri-rfid-line",
  "ri-rfid-fill",

  // Document
  "ri-file-line",
  "ri-file-fill",
  "ri-file-edit-line",
  "ri-file-edit-fill",
  "ri-file-list-2-line",
  "ri-file-list-2-fill",
  "ri-file-copy-2-line",
  "ri-file-copy-2-fill",
  "ri-clipboard-line",
  "ri-clipboard-fill",
  "ri-file-zip-line",
  "ri-file-zip-fill",
  "ri-file-mark-line",
  "ri-file-mark-fill",
  "ri-contacts-book-line",
  "ri-contacts-book-fill",
  "ri-file-pdf-2-line",
  "ri-file-pdf-2-fill",
  "ri-file-word-line",
  "ri-file-word-fill",
  "ri-file-ppt-line",
  "ri-file-ppt-fill",
  "ri-file-excel-line",
  "ri-file-excel-fill",
  "ri-keynote-line",
  "ri-keynote-fill",
  "ri-numbers-line",
  "ri-numbers-fill",
  "ri-file-search-line",
  "ri-file-search-fill",
  "ri-file-add-line",
  "ri-file-add-fill",
  "ri-file-reduce-line",
  "ri-file-reduce-fill",
  "ri-file-settings-line",
  "ri-file-settings-fill",
  "ri-file-image-line",
  "ri-file-image-fill",
  "ri-file-music-line",
  "ri-file-music-fill",
  "ri-file-video-line",
  "ri-file-video-fill",
  "ri-file-gif-line",
  "ri-file-gif-fill",
  "ri-folder-line",
  "ri-folder-fill",
  "ri-folder-add-line",
  "ri-folder-add-fill",
  "ri-folder-reduce-line",
  "ri-folder-reduce-fill",
  "ri-folder-settings-line",
  "ri-folder-settings-fill",
  "ri-folder-image-line",
  "ri-folder-image-fill",
  "ri-folder-music-line",
  "ri-folder-music-fill",
  "ri-folder-video-line",
  "ri-folder-video-fill",
  "ri-folder-zip-line",
  "ri-folder-zip-fill",
  "ri-markdown-line",
  "ri-markdown-fill",

  // Editor
  "ri-bold",
  "ri-italic",
  "ri-heading",
  "ri-text",
  "ri-font-family",
  "ri-font-sans-serif",
  "ri-font-sans",
  "ri-font-mono",
  "ri-font-color",
  "ri-font-size",
  "ri-font-size-2",
  "ri-underline",
  "ri-overline",
  "ri-emphasis",
  "ri-emphasis-cn",
  "ri-strikethrough",
  "ri-strikethrough-2",
  "ri-format-clear",
  "ri-align-left",
  "ri-align-center",
  "ri-align-right",
  "ri-align-justify",
  "ri-align-top",
  "ri-align-vertically",
  "ri-align-bottom",
  "ri-list-check",
  "ri-list-check-2",
  "ri-list-check-3",
  "ri-list-ordered",
  "ri-list-ordered-2",
  "ri-list-unordered",
  "ri-list-radio",
  "ri-list-indefinite",
  "ri-indent-decrease",
  "ri-indent-increase",
  "ri-line-height",
  "ri-text-spacing",
  "ri-text-wrap",
  "ri-attachment-2",
  "ri-link",
  "ri-link-unlink",
  "ri-link-m",
  "ri-link-unlink-m",
  "ri-separator",
  "ri-space",
  "ri-page-separator",
  "ri-code-view",
  "ri-quote-text",
  "ri-double-quotes-l",
  "ri-double-quotes-r",
  "ri-single-quotes-l",
  "ri-single-quotes-r",
  "ri-table-2",
  "ri-subscript",
  "ri-subscript-2",
  "ri-superscript",
  "ri-superscript-2",
  "ri-paragraph",
  "ri-text-direction-l",
  "ri-text-direction-r",
  "ri-functions",
  "ri-omega",
  "ri-hashtag",
  "ri-asterisk",
  "ri-question-mark",
  "ri-translate-2",
  "ri-a-b",
  "ri-english-input",
  "ri-pinyin-input",
  "ri-wubi-input",
  "ri-input-cursor-move",
  "ri-number-1",
  "ri-number-2",
  "ri-number-3",
  "ri-number-4",
  "ri-number-5",
  "ri-number-6",
  "ri-number-7",
  "ri-number-8",
  "ri-number-9",
  "ri-number-0",
  "ri-sort-asc",
  "ri-sort-desc",
  "ri-bring-forward",
  "ri-send-backward",
  "ri-bring-to-front",
  "ri-send-to-back",
  "ri-h-1",
  "ri-h-2",
  "ri-h-3",
  "ri-h-4",
  "ri-h-5",
  "ri-h-6",
  "ri-insert-column-left",
  "ri-insert-column-right",
  "ri-insert-row-top",
  "ri-insert-row-bottom",
  "ri-delete-column",
  "ri-delete-row",
  "ri-merge-cells-horizontal",
  "ri-merge-cells-vertical",
  "ri-split-cells-horizontal",
  "ri-split-cells-vertical",
  "ri-flow-chart",
  "ri-mind-map",
  "ri-node-tree",
  "ri-organization-chart",
  "ri-rounded-corner",
  "ri-sketching",
  "ri-draggable",
  "ri-slash-commands-2",
  "ri-ai-generate",
  "ri-dropdown-list",

  // Finance
  "ri-wallet-line",
  "ri-wallet-fill",
  "ri-coupon-line",
  "ri-coupon-fill",
  "ri-shopping-bag-line",
  "ri-shopping-bag-fill",
  "ri-shopping-cart-2-line",
  "ri-shopping-cart-2-fill",
  "ri-vip-crown-2-line",
  "ri-vip-crown-2-fill",
  "ri-trophy-line",
  "ri-trophy-fill",
  "ri-vip-diamond-line",
  "ri-vip-diamond-fill",
  "ri-gift-line",
  "ri-gift-fill",
  "ri-hand-coin-line",
  "ri-hand-coin-fill",

  // Health & Medical
  "ri-heart-2-line",
  "ri-heart-2-fill",
  "ri-flask-line",
  "ri-flask-fill",
  "ri-test-tube-line",
  "ri-test-tube-fill",
  
  // Logos
  "ri-alipay-line",
  "ri-alipay-fill",
  "ri-android-line",
  "ri-android-fill",
  "ri-app-store-line",
  "ri-app-store-fill",
  "ri-baidu-line",
  "ri-baidu-fill",
  "ri-bilibili-line",
  "ri-chrome-line",
  "ri-codepen-line",
  "ri-dingding-line",
  "ri-dingding-fill",
  "ri-discord-line",
  "ri-discord-fill",
  "ri-dribbble-line",
  "ri-drive-line",
  "ri-drive-fill",
  "ri-github-line",
  "ri-github-fill",
  "ri-gitlab-line",
  "ri-gitlab-fill",
  "ri-google-line",
  "ri-instagram-line",
  "ri-meta-line",
  "ri-mini-program-line",
  "ri-mini-program-fill",
  "ri-notion-line",
  "ri-npmjs-line",
  "ri-qq-line",
  "ri-qq-fill",
  "ri-reactjs-line",
  "ri-remixicon-line",
  "ri-remixicon-fill",
  "ri-stack-overflow-line",
  "ri-switch-line",
  "ri-taobao-fill",
  "ri-tiktok-line",
  "ri-tiktok-fill",
  "ri-twitter-line",
  "ri-twitter-fill",
  "ri-twitter-x-line",
  "ri-twitter-x-fill",
  "ri-vuejs-line",
  "ri-vuejs-fill",
  "ri-wechat-line",
  "ri-wechat-fill",
  "ri-wechat-pay-line",
  "ri-wechat-pay-fill",
  "ri-weibo-line",
  "ri-weibo-fill",
  "ri-windows-line",
  "ri-windows-fill",
  "ri-youtube-line",
  "ri-youtube-fill",
  "ri-zhihu-line",
  "ri-zhihu-fill",

  // Map
  "ri-map-pin-line",
  "ri-map-pin-fill",
  "ri-road-map-line",
  "ri-road-map-fill",
  "ri-planet-line",
  "ri-planet-fill",
  "ri-taxi-line",
  "ri-taxi-fill",
  "ri-bus-line",
  "ri-bus-fill",
  "ri-truck-line",
  "ri-truck-fill",
  "ri-plane-line",
  "ri-plane-fill",
  "ri-ship-2-line",
  "ri-ship-2-fill",
  "ri-walk-line",
  "ri-run-line",
  "ri-riding-line",
  "ri-footprint-line",
  "ri-footprint-fill",
  "ri-restaurant-2-line",
  "ri-restaurant-2-fill",
  "ri-cup-line",
  "ri-cup-fill",
  "ri-navigation-line",
  "ri-navigation-fill",

  // Media
  "ri-image-line",
  "ri-image-fill",
  "ri-image-add-line",
  "ri-image-add-fill",
  "ri-image-edit-line",
  "ri-image-edit-fill",
  "ri-video-line",
  "ri-video-fill",
  "ri-camera-line",
  "ri-camera-fill",
  "ri-music-2-line",
  "ri-music-2-fill",
  "ri-headphone-line",
  "ri-headphone-fill",
  "ri-mic-line",
  "ri-mic-fill",
  "ri-mic-off-line",
  "ri-mic-off-fill",
  "ri-volume-down-line",
  "ri-volume-down-fill",
  "ri-volume-mute-line",
  "ri-volume-mute-fill",
  "ri-volume-up-line",
  "ri-volume-up-fill",
  "ri-volume-vibrate-line",
  "ri-volume-vibrate-fill",
  "ri-volume-off-vibrate-line",
  "ri-volume-off-vibrate-fill",
  "ri-notification-4-line",
  "ri-notification-4-fill",
  "ri-notification-off-line",
  "ri-notification-off-fill",
  "ri-play-line",
  "ri-play-fill",
  "ri-pause-line",
  "ri-pause-fill",
  "ri-stop-line",
  "ri-stop-fill",
  "ri-rewind-line",
  "ri-rewind-fill",
  "ri-speed-line",
  "ri-speed-fill",
  "ri-skip-back-line",
  "ri-skip-back-fill",
  "ri-skip-forward-line",
  "ri-skip-forward-fill",
  "ri-repeat-2-line",
  "ri-shuffle-line",
  "ri-fullscreen-line",
  "ri-fullscreen-exit-line",
  "ri-equalizer-line",
  "ri-equalizer-fill",
  "ri-sound-module-line",
  "ri-voiceprint-line",

  // System
  "ri-function-line",
  "ri-function-fill",
  "ri-menu-line",
  "ri-menu-fold-line",
  "ri-menu-unfold-line",
  "ri-more-line",
  "ri-settings-2-line",
  "ri-settings-2-fill",
  "ri-prohibited-line",
  "ri-prohibited-fill",
  "ri-information-line",
  "ri-information-fill",
  "ri-error-warning-line",
  "ri-error-warning-fill",
  "ri-question-line",
  "ri-question-fill",
  "ri-checkbox-line",
  "ri-checkbox-fill",
  "ri-checkbox-indeterminate-line",
  "ri-checkbox-indeterminate-fill",
  "ri-add-box-line",
  "ri-add-box-fill",
  "ri-indeterminate-circle-line",
  "ri-indeterminate-circle-fill",
  "ri-add-circle-line",
  "ri-add-circle-fill",
  "ri-check-line",
  "ri-close-line",
  "ri-add-line",
  "ri-subtract-line",
  "ri-divide-line",
  "ri-download-line",
  "ri-download-fill",
  "ri-upload-line",
  "ri-upload-fill",
  "ri-download-cloud-line",
  "ri-download-cloud-fill",
  "ri-login-box-line",
  "ri-logout-box-line",
  "ri-login-circle-line",
  "ri-logout-circle-line",
  "ri-refresh-line",
  "ri-delete-bin-line",
  "ri-delete-bin-fill",
  "ri-lock-line",
  "ri-lock-fill",
  "ri-eye-line",
  "ri-eye-fill",
  "ri-eye-close-line",
  "ri-eye-close-fill",
  "ri-search-2-line",
  "ri-search-2-fill",
  "ri-zoom-in-line",
  "ri-zoom-in-fill",
  "ri-zoom-out-line",
  "ri-zoom-out-fill",
  "ri-share-line",
  "ri-share-fill",
  "ri-time-line",
  "ri-time-fill",
  "ri-hourglass-line",
  "ri-hourglass-fill",
  "ri-thumb-up-line",
  "ri-thumb-up-fill",
  "ri-thumb-down-line",
  "ri-thumb-down-fill",
  "ri-alarm-warning-line",
  "ri-alarm-warning-fill",
  "ri-filter-line",
  "ri-filter-fill",
  "ri-loader-line",
  "ri-loop-left-line",

  // User & Faces
  "ri-user-3-line",
  "ri-user-3-fill",
  "ri-account-box-line",
  "ri-account-box-fill",
  "ri-account-circle-line",
  "ri-account-circle-fill",
  "ri-group-line",
  "ri-group-fill",
  "ri-team-line",
  "ri-team-fill",
  "ri-men-line",
  "ri-men-fill",
  "ri-women-line",
  "ri-women-fill",
  "ri-spy-line",
  "ri-spy-fill",

  // Weather
  "ri-sun-line",
  "ri-sun-fill",
  "ri-moon-line",
  "ri-moon-fill",
  "ri-flashlight-line",
  "ri-flashlight-fill",
  "ri-cloudy-2-line",
  "ri-cloudy-2-fill",
  "ri-mist-line",
  "ri-foggy-line",
  "ri-foggy-fill",
  "ri-cloud-windy-line",
  "ri-cloud-windy-fill",
  "ri-windy-line",
  "ri-windy-fill",
  "ri-rainy-line",
  "ri-rainy-fill",
  "ri-drizzle-line",
  "ri-drizzle-fill",
  "ri-showers-line",
  "ri-showers-fill",
  "ri-heavy-showers-line",
  "ri-heavy-showers-fill",
  "ri-thunderstorms-line",
  "ri-thunderstorms-fill",
  "ri-hail-line",
  "ri-hail-fill",
  "ri-snowy-line",
  "ri-snowy-fill",
  "ri-sun-cloudy-line",
  "ri-sun-cloudy-fill",
  "ri-moon-cloudy-line",
  "ri-moon-cloudy-fill",
  "ri-tornado-line",
  "ri-tornado-fill",
  "ri-typhoon-line",
  "ri-typhoon-fill",
  "ri-haze-line",
  "ri-haze-fill",
  "ri-sun-foggy-line",
  "ri-sun-foggy-fill",
  "ri-moon-foggy-line",
  "ri-moon-foggy-fill",
  "ri-moon-clear-line",
  "ri-moon-clear-fill",
  "ri-temp-hot-line",
  "ri-temp-hot-fill",
  "ri-temp-cold-line",
  "ri-temp-cold-fill",
  "ri-celsius-line",
  "ri-fahrenheit-line",
  "ri-water-percent-line",
  "ri-water-percent-fill",
  "ri-fire-line",
  "ri-fire-fill",
  "ri-blaze-line",
  "ri-blaze-fill",
  "ri-earthquake-line",
  "ri-earthquake-fill",
  "ri-flood-line",
  "ri-flood-fill",
  "ri-meteor-line",
  "ri-meteor-fill",
  "ri-rainbow-line",
  "ri-rainbow-fill",
  "ri-shining-line",
  "ri-shining-fill",
  "ri-sparkling-line",
  "ri-sparkling-fill",

  // Others
  "ri-basketball-line",
  "ri-basketball-fill",
  "ri-bell-line",
  "ri-bell-fill",
  "ri-billiards-line",
  "ri-billiards-fill",
  "ri-boxing-line",
  "ri-boxing-fill",
  "ri-cake-2-line",
  "ri-cake-2-fill",
  "ri-door-lock-line",
  "ri-door-lock-fill",
  "ri-door-lock-box-line",
  "ri-door-lock-box-fill",
  "ri-football-line",
  "ri-football-fill",
  "ri-game-line",
  "ri-game-fill",
  "ri-handbag-line",
  "ri-handbag-fill",
  "ri-key-2-line",
  "ri-key-2-fill",
  "ri-knife-line",
  "ri-knife-fill",
  "ri-knife-blood-line",
  "ri-knife-blood-fill",
  "ri-lightbulb-line",
  "ri-lightbulb-fill",
  "ri-lightbulb-flash-line",
  "ri-lightbulb-flash-fill",
  "ri-outlet-2-line",
  "ri-outlet-2-fill",
  "ri-plug-line",
  "ri-plug-fill",
  "ri-ping-pong-line",
  "ri-ping-pong-fill",
  "ri-reserved-line",
  "ri-reserved-fill",
  "ri-shirt-line",
  "ri-shirt-fill",
  "ri-sword-line",
  "ri-sword-fill",
  "ri-t-shirt-line",
  "ri-t-shirt-fill",
  "ri-t-shirt-air-line",
  "ri-t-shirt-air-fill",
  "ri-umbrella-line",
  "ri-umbrella-fill",
  "ri-character-recognition-line",
  "ri-character-recognition-fill",
  "ri-voice-recognition-line",
  "ri-voice-recognition-fill",
  "ri-leaf-line",
  "ri-leaf-fill",
  "ri-plant-line",
  "ri-plant-fill",
  "ri-seedling-line",
  "ri-seedling-fill",
  "ri-tree-line",
  "ri-tree-fill",
  "ri-recycle-line",
  "ri-recycle-fill",
  "ri-scales-3-line",
  "ri-scales-3-fill",
  "ri-fridge-line",
  "ri-fridge-fill",
  "ri-wheelchair-line",
  "ri-wheelchair-fill",
  "ri-cactus-line",
  "ri-cactus-fill",
  "ri-door-line",
  "ri-door-fill",
  "ri-door-open-line",
  "ri-door-open-fill",
  "ri-door-closed-line",
  "ri-door-closed-fill",
  "ri-graduation-cap-line",
  "ri-graduation-cap-fill",
  "ri-box-3-line",
  "ri-box-3-fill",
  "ri-candle-line",
  "ri-candle-fill",
  "ri-cross-line",
  "ri-cross-fill",
  "ri-infinity-line",
  "ri-infinity-fill"
]

// 快速选取https://remixicon.com网址上的图标
 const getRemixIcons = () => {
  // 过滤需要的图标
  let list = Array.from(document.querySelectorAll(".rd-icon-add")).filter(item => {
    const icon = item.parentElement.querySelector("i")
    return icons.includes(icon.className)
  });
  // 点击加入下载列表中
  list.forEach(item => { setTimeout(() => { item.click();},0)})
}

const fs = require('node:fs')
const path = require('node:path')

const getIconNames = (css) => {
  return css
          .split('.adorn-icon-')
          .map(item => {
            const [name] = item.split('::before')
            console.log(name)
            return name
          })
          .filter(Boolean)
          .map(item => `"${item}"`)
          .join("|")
}

const replaceIconsNames = () => {
  let filepath = path.resolve(__dirname,'../packages/adorn-ui/src/Icon/fonts/remixicon.css')
  let css = fs.readFileSync(filepath,"utf-8") 

  css = css
          // 替换掉前缀
          .replace(/ri-/g,"adorn-icon-")
          // 移除-line，让图标默认的就是线性图标
          .replace(/-line/g, "")
          // 移除-数字
          .replace(/-\d/g,'')

  Array.from({length:10}).forEach((_,index) => {
    if(index === 9){
      css = css.replace('.adorn-icon-number::before',`.adorn-icon-number-0::before`)
      return
    }
    css = css.replace('.adorn-icon-h::before',`.adorn-icon-h-${index + 1}::before`)
             .replace('.adorn-icon-number::before',`.adorn-icon-number-${index + 1}::before`)
  })

  // 客服图标
  css = css.replace("adorn-icon-customer-service","adorn-icon-customer")
  css = css.replace("adorn-icon-customer-service-fill","adorn-icon-customer-fill")
  // 徽章
  css = css.replace("adorn-icon-verified-badge","adorn-icon-badge")
  css = css.replace("adorn-icon-verified-badge-fill","adorn-icon-badge-fill")
  // code
  css = css.replace("adorn-icon-code-s-slash","adorn-icon-code")
  css = css.replace("adorn-icon-code-s-slash-fill","adorn-icon-code-fill")
  // terminal
  css = css.replace("adorn-icon-terminal-box","adorn-icon-terminal")
  css = css.replace("adorn-icon-terminal-box-fill","adorn-icon-terminal-fill")
  // map
  css = css.replace("adorn-icon-map-pin","adorn-icon-map")
  css = css.replace("adorn-icon-map-pin-fill","adorn-icon-map-fill")
  // info
  css = css.replace("adorn-icon-information","adorn-icon-info")
  css = css.replace("adorn-icon-information-fill","adorn-icon-info")
  // warning
  css = css.replace("adorn-icon-error-warning","adorn-warning")
  css = css.replace("adorn-icon-error-warning-fill","adorn-icon-warning-fill")


  let types = getIconNames(css)
  console.log("========类型========")
  console.log(types)
  console.log("========类型========")
  console.log()
  console.log("========名称========")
  console.log(types.replaceAll('|',","))
  console.log("========名称========")

  fs.writeFileSync(filepath,css)
}

replaceIconsNames()

